/** Built-in curated themes registered by the theme plugin beyond light/dark. */

import type { ThemeDefinition } from './client/index.ts'

/**
 * Curated product themes. Each carries a slim, high-contrast token set — the
 * surfaces, text, accent, borders, and status colors a theme must decide — and
 * lets the base palette supply the rest. A theme may add a small raw stylesheet
 * for what tokens cannot express; built-ins use it only for selection ink so a
 * theme stays a few hundred bytes with no webfont or image payload.
 */
export const CURATED_THEMES: readonly ThemeDefinition[] = [
  {
    id: 'neon-purple',
    name: '霓虹紫黑',
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#0a0a14',
      '--dsw-alias-bg-layer-1': '#12121f',
      '--dsw-alias-bg-layer-2': '#1a1a2c',
      '--dsw-alias-bg-overlay': '#1a1a2c',
      '--dsw-specific-sidebar-fill': '#0d0d18',
      '--dsw-alias-label-primary': '#f0eefc',
      '--dsw-alias-label-secondary': '#9a97c9',
      '--dsw-alias-brand-primary': '#a855f7',
      '--dsw-alias-brand-text': '#0a0a14',
      '--dsw-alias-label-primary-foreground': '#0a0a14',
      '--dsw-alias-label-primary-inverted': '#0a0a14',
      '--dsw-alias-button-info-fill': '#a855f7',
      '--dsw-alias-button-info-hover': '#b87af9',
      '--dsw-alias-border-l1': 'rgba(168,85,247,0.28)',
      '--dsw-alias-border-l2': 'rgba(168,85,247,0.5)',
      '--dsw-alias-state-error-primary': '#ff4d6d',
      '--dsw-alias-state-success-primary': '#22d3ee',
      '--dsw-alias-state-warn-primary': '#fbbf24',
    },
    css: '::selection{background:#a855f7;color:#0a0a14}',
  },
  {
    id: 'terminal-green',
    name: '终端绿黑',
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#000000',
      '--dsw-alias-bg-layer-1': '#0a0a0a',
      '--dsw-alias-bg-layer-2': '#131313',
      '--dsw-alias-bg-overlay': '#131313',
      '--dsw-specific-sidebar-fill': '#050505',
      '--dsw-alias-label-primary': '#d6ffd6',
      '--dsw-alias-label-secondary': '#7fbf7f',
      '--dsw-alias-brand-primary': '#00ff66',
      '--dsw-alias-brand-text': '#000000',
      '--dsw-alias-label-primary-foreground': '#000000',
      '--dsw-alias-label-primary-inverted': '#000000',
      '--dsw-alias-button-info-fill': '#00ff66',
      '--dsw-alias-button-info-hover': '#33ff85',
      '--dsw-alias-border-l1': 'rgba(0,255,102,0.28)',
      '--dsw-alias-border-l2': 'rgba(0,255,102,0.55)',
      '--dsw-alias-state-error-primary': '#ff4d4d',
      '--dsw-alias-state-success-primary': '#00ff66',
      '--dsw-alias-state-warn-primary': '#ffcc00',
    },
    css: '::selection{background:#00ff66;color:#000000}',
  },
  {
    id: 'sunset',
    name: '日落橙紫',
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#1a0f14',
      '--dsw-alias-bg-layer-1': '#241322',
      '--dsw-alias-bg-layer-2': '#2e1a2b',
      '--dsw-alias-bg-overlay': '#2e1a2b',
      '--dsw-specific-sidebar-fill': '#120a10',
      '--dsw-alias-label-primary': '#ffe8d9',
      '--dsw-alias-label-secondary': '#c9a6b8',
      '--dsw-alias-brand-primary': '#ff7a18',
      '--dsw-alias-brand-text': '#1a0f14',
      '--dsw-alias-label-primary-foreground': '#1a0f14',
      '--dsw-alias-label-primary-inverted': '#1a0f14',
      '--dsw-alias-button-info-fill': '#ff7a18',
      '--dsw-alias-button-info-hover': '#ff8f3d',
      '--dsw-alias-border-l1': 'rgba(255,122,24,0.3)',
      '--dsw-alias-border-l2': 'rgba(255,122,24,0.55)',
      '--dsw-alias-state-error-primary': '#ff4d6d',
      '--dsw-alias-state-success-primary': '#7ce495',
      '--dsw-alias-state-warn-primary': '#ffd166',
    },
    css: '::selection{background:#ff7a18;color:#1a0f14}',
  },
  {
    id: 'mint-pink',
    name: '薄荷粉撞',
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#f4fbf7',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#eef8f2',
      '--dsw-alias-bg-overlay': '#ffffff',
      '--dsw-specific-sidebar-fill': '#e9f5ee',
      '--dsw-alias-label-primary': '#14332a',
      '--dsw-alias-label-secondary': '#4e7a6a',
      '--dsw-alias-brand-primary': '#ff3d81',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-label-primary-foreground': '#ffffff',
      '--dsw-alias-label-primary-inverted': '#ffffff',
      '--dsw-alias-button-info-fill': '#ff3d81',
      '--dsw-alias-button-info-hover': '#ff5c97',
      '--dsw-alias-border-l1': 'rgba(20,51,42,0.16)',
      '--dsw-alias-border-l2': 'rgba(255,61,129,0.4)',
      '--dsw-alias-state-error-primary': '#e53935',
      '--dsw-alias-state-success-primary': '#16a36a',
      '--dsw-alias-state-warn-primary': '#f59f00',
    },
    css: '::selection{background:#ff3d81;color:#ffffff}',
  },
]
