/** Built-in curated themes registered by the theme plugin beyond light/dark. */

import type { ThemeDefinition } from './client/index.ts'

/**
 * Curated product themes. Each is a self-contained token dictionary plus an
 * optional raw stylesheet for what tokens cannot express (halftone texture,
 * page zoom, selection ink). Fonts use system stacks only, so a theme stays a
 * few kilobytes with no webfont or image payload.
 */
export const CURATED_THEMES: readonly ThemeDefinition[] = [
  {
    id: 'editor-dark',
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#0f1116',
      '--dsw-alias-bg-layer-1': '#161922',
      '--dsw-alias-bg-layer-2': '#1d2230',
      '--dsw-alias-bg-layer-3': '#252b3b',
      '--dsw-alias-bg-overlay': '#252b3b',
      '--dsw-alias-border-l1': 'rgba(255,255,255,0.06)',
      '--dsw-alias-border-l2': 'rgba(255,255,255,0.10)',
      '--dsw-alias-border-l3': 'rgba(255,255,255,0.14)',
      '--dsw-alias-border-l4': 'rgba(255,255,255,0.20)',
      '--dsw-alias-brand-primary': '#4d9fff',
      '--dsw-alias-brand-text': '#e9f2ff',
      '--dsw-alias-button-primary-fill': '#4d9fff',
      '--dsw-alias-button-primary-hover': '#63aaff',
      '--dsw-alias-button-info-fill': '#2f6fc9',
      '--dsw-alias-button-info-hover': '#3b82e0',
      '--dsw-alias-button-elevated-fill': '#161922',
      '--dsw-alias-button-floating-fill': '#1d2230',
      '--dsw-alias-button-floating-hover': '#252b3b',
      '--dsw-alias-button-ghost-active-fill': '#252b3b',
      '--dsw-alias-button-ghost-active-hover': '#1d2230',
      '--dsw-alias-button-tool-bar-fill': 'rgba(255,255,255,0.08)',
      '--dsw-alias-button-tool-bar-hover': 'rgba(255,255,255,0.12)',
      '--dsw-alias-button-contrast-fill': '#e8ecf4',
      '--dsw-alias-interactive-bg-hover': 'rgba(255,255,255,0.06)',
      '--dsw-alias-interactive-bg-active': 'rgba(255,255,255,0.10)',
      '--dsw-alias-interactive-bg-hover-solid': '#1d2230',
      '--dsw-alias-label-primary': '#eef1f7',
      '--dsw-alias-label-secondary': '#9aa5bd',
      '--dsw-alias-label-tertiary': '#6b7689',
      '--dsw-alias-label-caption': '#5c6677',
      '--dsw-alias-label-primary-foreground': '#0b0d12',
      '--dsw-alias-label-primary-inverted': '#0b0d12',
      '--dsw-alias-markdown-code-block': '#141821',
      '--dsw-alias-markdown-code-block-banner': '#1a1f2c',
      '--dsw-alias-markdown-inline-code': '#1d2230',
      '--dsw-alias-scrollbar-bg-l1': '#2a3142',
      '--dsw-alias-scrollbar-hover-l1': '#3a4254',
      '--dsw-alias-state-error-primary': '#ff6b6b',
      '--dsw-alias-state-success-primary': '#42d392',
      '--dsw-alias-state-warn-primary': '#ffc75c',
      '--dsw-alias-toast-bg': '#1d2230',
      '--dsw-alias-tooltip-bg': '#252b3b',
      '--dsw-specific-bubble': '#161922',
      '--dsw-specific-bubble-highlight': '#1d2230',
      '--dsw-specific-input-major': '#141821',
      '--dsw-specific-menu': '#252b3b',
      '--dsw-specific-sidebar-fill': '#12151d',
      '--dsw-specific-sidebar-nav-item-active': '#1d2230',
      '--dsw-specific-sidebar-nav-item-active-accent': '#4d9fff',
      '--dsw-specific-sidebar-nav-item-hover': '#161922',
      '--dsl-web-radius': '6px',
      '--dsw-shadow-lv1': '0 1px 2px 0 rgba(0,0,0,0.45)',
      '--dsw-shadow-lv2': '0 2px 8px 0 rgba(0,0,0,0.40)',
      '--dsw-shadow-lv3': '0 0 0 1px rgba(255,255,255,0.06), 0 12px 28px 0 rgba(0,0,0,0.55)',
      '--shiki-foreground': '#eef1f7',
      '--shiki-background': '#141821',
      '--shiki-token-constant': '#4dabf7',
      '--shiki-token-string': '#69db7c',
      '--shiki-token-comment': '#7c86a0',
      '--shiki-token-keyword': '#faa2c1',
      '--shiki-token-parameter': '#ffa94d',
      '--shiki-token-function': '#b197fc',
      '--shiki-token-punctuation': '#9aa5bd',
      '--shiki-token-link': '#74c0fc',
    },
    css: [
      'body{-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}',
      '::selection{background:rgba(77,159,255,0.35);color:#ffffff}',
    ].join(''),
  },
  {
    id: 'manga-ink',
    colorScheme: 'dark',
    tokens: {
      '--dsw-alias-bg-base': '#0d0d12',
      '--dsw-alias-bg-layer-1': '#131319',
      '--dsw-alias-bg-layer-2': '#191920',
      '--dsw-alias-bg-layer-3': '#202029',
      '--dsw-alias-bg-overlay': '#202029',
      '--dsw-alias-border-l1': 'rgba(255,255,255,0.12)',
      '--dsw-alias-border-l2': 'rgba(255,255,255,0.22)',
      '--dsw-alias-border-l3': 'rgba(255,255,255,0.30)',
      '--dsw-alias-border-l4': 'rgba(255,255,255,0.42)',
      '--dsw-alias-brand-primary': '#ffd60a',
      '--dsw-alias-brand-text': '#0d0d12',
      '--dsw-alias-button-primary-fill': '#ffd60a',
      '--dsw-alias-button-primary-hover': '#ffe14d',
      '--dsw-alias-button-info-fill': '#00c8e6',
      '--dsw-alias-button-info-hover': '#2ee6ff',
      '--dsw-alias-button-elevated-fill': '#131319',
      '--dsw-alias-button-floating-fill': '#191920',
      '--dsw-alias-button-floating-hover': '#202029',
      '--dsw-alias-button-ghost-active-fill': '#202029',
      '--dsw-alias-button-ghost-active-hover': '#191920',
      '--dsw-alias-button-tool-bar-fill': 'rgba(255,255,255,0.10)',
      '--dsw-alias-button-tool-bar-hover': 'rgba(255,255,255,0.16)',
      '--dsw-alias-button-contrast-fill': '#f4f4f8',
      '--dsw-alias-interactive-bg-hover': 'rgba(255,255,255,0.07)',
      '--dsw-alias-interactive-bg-active': 'rgba(255,255,255,0.12)',
      '--dsw-alias-interactive-bg-hover-solid': '#191920',
      '--dsw-alias-label-primary': '#f4f4f8',
      '--dsw-alias-label-secondary': '#a8a8b8',
      '--dsw-alias-label-tertiary': '#70707f',
      '--dsw-alias-label-caption': '#5a5a68',
      '--dsw-alias-label-primary-foreground': '#0d0d12',
      '--dsw-alias-label-primary-inverted': '#0d0d12',
      '--dsw-alias-markdown-code-block': '#101016',
      '--dsw-alias-markdown-code-block-banner': '#16161e',
      '--dsw-alias-markdown-inline-code': '#191920',
      '--dsw-alias-scrollbar-bg-l1': 'rgba(255,214,10,0.45)',
      '--dsw-alias-scrollbar-hover-l1': '#ffd60a',
      '--dsw-alias-state-error-primary': '#ff2e4d',
      '--dsw-alias-state-success-primary': '#39d98a',
      '--dsw-alias-state-warn-primary': '#ff9f1a',
      '--dsw-alias-toast-bg': '#191920',
      '--dsw-alias-tooltip-bg': '#202029',
      '--dsw-specific-bubble': '#131319',
      '--dsw-specific-bubble-highlight': '#1a1a22',
      '--dsw-specific-input-major': '#101016',
      '--dsw-specific-menu': '#202029',
      '--dsw-specific-sidebar-fill': '#0a0a0f',
      '--dsw-specific-sidebar-nav-item-active': '#1a1a22',
      '--dsw-specific-sidebar-nav-item-active-accent': '#ffd60a',
      '--dsw-specific-sidebar-nav-item-hover': '#131319',
      '--dsl-web-radius': '8px',
      '--dsw-shadow-lv1': '0 0 0 1px rgba(240,240,245,0.45)',
      '--dsw-shadow-lv2': '0 0 0 1px rgba(240,240,245,0.70), 3px 3px 0 0 rgba(255,255,255,0.14)',
      '--dsw-shadow-lv3': '0 0 0 2px rgba(240,240,245,0.90), 5px 5px 0 0 rgba(255,214,10,0.50)',
      '--shiki-foreground': '#f4f4f8',
      '--shiki-background': '#101016',
      '--shiki-token-constant': '#2ee6ff',
      '--shiki-token-string': '#69db7c',
      '--shiki-token-comment': '#8a8a9a',
      '--shiki-token-keyword': '#ff5c9e',
      '--shiki-token-parameter': '#ffb84d',
      '--shiki-token-function': '#c0a4ff',
      '--shiki-token-punctuation': '#a8a8b8',
      '--shiki-token-link': '#74c0fc',
    },
    css: [
      'body{-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;background-image:radial-gradient(rgba(255,255,255,0.055) 1px,transparent 1.4px);background-size:16px 16px}',
      '::selection{background:#ffd60a;color:#0d0d12}',
      ':focus-visible{outline:2px solid #ffd60a;outline-offset:2px}',
    ].join(''),
  },
  {
    id: 'pencil-paper',
    colorScheme: 'light',
    tokens: {
      '--dsw-alias-bg-base': '#f5f2ea',
      '--dsw-alias-bg-layer-1': '#ffffff',
      '--dsw-alias-bg-layer-2': '#fbfaf5',
      '--dsw-alias-bg-layer-3': '#ffffff',
      '--dsw-alias-bg-overlay': '#ffffff',
      '--dsw-alias-border-l1': 'rgba(0,0,0,0.16)',
      '--dsw-alias-border-l2': 'rgba(0,0,0,0.28)',
      '--dsw-alias-border-l3': 'rgba(0,0,0,0.36)',
      '--dsw-alias-border-l4': 'rgba(0,0,0,0.50)',
      '--dsw-alias-brand-primary': '#1a1a1a',
      '--dsw-alias-brand-text': '#ffffff',
      '--dsw-alias-button-primary-fill': '#1a1a1a',
      '--dsw-alias-button-primary-hover': '#3a3a3a',
      '--dsw-alias-button-info-fill': '#1a1a1a',
      '--dsw-alias-button-info-hover': '#3a3a3a',
      '--dsw-alias-button-elevated-fill': '#ffffff',
      '--dsw-alias-button-floating-fill': '#ffffff',
      '--dsw-alias-button-floating-hover': '#f5f2ea',
      '--dsw-alias-button-ghost-active-fill': '#e8e6df',
      '--dsw-alias-button-ghost-active-hover': '#f1efe8',
      '--dsw-alias-button-tool-bar-fill': 'rgba(0,0,0,0.06)',
      '--dsw-alias-button-tool-bar-hover': 'rgba(0,0,0,0.10)',
      '--dsw-alias-button-contrast-fill': '#1a1a1a',
      '--dsw-alias-interactive-bg-hover': 'rgba(0,0,0,0.05)',
      '--dsw-alias-interactive-bg-active': 'rgba(0,0,0,0.08)',
      '--dsw-alias-interactive-bg-hover-solid': '#f1efe8',
      '--dsw-alias-label-primary': '#1a1a1a',
      '--dsw-alias-label-secondary': '#55554f',
      '--dsw-alias-label-tertiary': '#75756e',
      '--dsw-alias-label-caption': '#8a8a82',
      '--dsw-alias-label-primary-foreground': '#ffffff',
      '--dsw-alias-label-primary-inverted': '#ffffff',
      '--dsw-alias-markdown-code-block': '#f1efe8',
      '--dsw-alias-markdown-inline-code': '#edeae1',
      '--dsw-alias-scrollbar-bg-l1': '#c9c7be',
      '--dsw-alias-scrollbar-hover-l1': '#9a988f',
      '--dsw-alias-state-error-primary': '#c02323',
      '--dsw-alias-state-success-primary': '#1f7a3d',
      '--dsw-alias-state-warn-primary': '#a66a00',
      '--dsw-alias-toast-bg': '#ffffff',
      '--dsw-alias-tooltip-bg': '#ffffff',
      '--dsw-specific-bubble': '#ffffff',
      '--dsw-specific-bubble-highlight': '#f5f2ea',
      '--dsw-specific-input-major': '#ffffff',
      '--dsw-specific-menu': '#ffffff',
      '--dsw-specific-sidebar-fill': '#edeae1',
      '--dsw-specific-sidebar-nav-item-active': '#ffffff',
      '--dsw-specific-sidebar-nav-item-active-accent': '#1a1a1a',
      '--dsw-specific-sidebar-nav-item-hover': '#f1efe8',
      '--dsw-font-family': "'Segoe Print', 'Bradley Hand', 'Comic Sans MS', 'Marker Felt', '楷体', 'KaiTi', '幼圆', 'YouYuan', cursive",
      '--dsw-font-markdown-base-font-family': "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif",
      '--dsw-font-markdown-h1-font-family': "'Segoe Print', 'Bradley Hand', 'Comic Sans MS', '楷体', 'KaiTi', cursive",
      '--dsl-web-radius': '10px',
      '--dsw-shadow-lv1': '0 0 0 1px rgba(0,0,0,0.18)',
      '--dsw-shadow-lv2': '0 0 0 1.5px rgba(26,26,26,0.55), 2px 2px 0 0 rgba(0,0,0,0.15)',
      '--dsw-shadow-lv3': '0 0 0 1.5px rgba(26,26,26,0.75), 3px 3px 0 0 rgba(0,0,0,0.22)',
      '--shiki-foreground': '#1a1a1a',
      '--shiki-background': '#f1efe8',
      '--shiki-token-constant': '#1c4e80',
      '--shiki-token-string': '#1f7a3d',
      '--shiki-token-comment': '#8a8a82',
      '--shiki-token-keyword': '#8a1c6e',
      '--shiki-token-parameter': '#a66a00',
      '--shiki-token-function': '#5b3bb0',
      '--shiki-token-punctuation': '#55554f',
      '--shiki-token-link': '#1c4e80',
    },
    css: [
      'html{zoom:1.12}',
      'body{-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}',
      'body::after{content:\'\';position:fixed;inset:0;z-index:2147483647;pointer-events:none;background-image:radial-gradient(rgba(0,0,0,0.06) 1px,transparent 1.6px);background-size:10px 10px}',
      '::selection{background:#1a1a1a;color:#ffffff}',
      ':focus-visible{outline:2px solid #1a1a1a;outline-offset:2px}',
    ].join(''),
  },
]
